### ISSUE TITLE
CV results and Classification report .csv files

### ISSUE THREAD

**Issue by nicovandenhooff** [UBC-MDS/online-shoppers-purchasing-intention#24]
Just noticed that our git ignore file ignores all .csv files (which is correct since we want to ignore the data files).  

In the model selection and model tuning scripts I had outputted the classification report and cross validation results as .csv files but they've been ignored by git.  

Making a note here so that I remember to fix this tomorrow so that these results can actually get pushed to the `results` folder for reference later in our Jupyter book.

**Comment by ytz** [comment]
You can also output as `pickle` or [Feather](https://arrow.apache.org/docs/python/feather.html) as an alternative.

Anyway, I'm not that familiar with Jupyter book yet. Am I right to assume that we are using Jupyter Notebook format (`.ipynb`) for the modelling section in our Jupyter book, instead of markdown?

**Comment by nicovandenhooff** [comment]
Awesome thanks @ytz I will look into those formats.  I’m actually not very familiar with jupyter book either.  But I think we can abstract away our modelling code, based on Tiff’s example repo I believe the book/report only needs to contain a qualitative assessment/discussion of the model and the results, but correct me if I’m wrong!

**Comment by nicovandenhooff** [comment]
Fixed with .html instead of .csv
