### ISSUE TITLE
Data Pre-processing script

### ISSUE THREAD

**Issue by ytz** [UBC-MDS/online-shoppers-purchasing-intention#9]

**Comment by nicovandenhooff** [comment]
@ytz let's connect tomorrow sometimes in terms of syncing the work between our scripts + feature engineering.  

After reviewing the milestone document I think it makes sense to include feature engineering in your data clean/pre-process/transforming script and then my script can then focus on taking the prepared data and performing model selection/model building, but we can chat details tomorrow.

**Comment by ytz** [comment]
@nicovandenhooff some high-level thoughts:

The output of the preprocessing script will be a cleaned `train.csv` and `test.csv` in `data/processed/`. You can assume the clean data has numeric columns without NULL. Essentially you can just plug it into ML algo straightaway.

* The train-test split will be done by chronological order (i.e. test starts towards the end of the year)
* `Month` column will be dropped. Don't think it is useful for modelling
* Some light feature engineering and transformation (e.g. OHE) will be done

I should be able to merge and initial version by this afternoon. We can then iterate on it by adding more features or transformation if needed.

_Note: Some features have outliers. Not too sure what to do with it for now. We can discuss further tmr._

**Comment by nicovandenhooff** [comment]
Awesome - thanks @ytz that sounds great thanks for the info.  I was planning to work on the ML piece this evening so your plan to work on the script in the afternoon fits perfectly with my plan.

I was thinking for today we can keep the analysis high level (given time restrictions with the Saturday deadline) and train "quick and dirty" models, then later in the week or even a future milestone we can iterate and deal with outliers/add new features etc.  but just a thought.

**Comment by arijeetchatterjee** [comment]
Hi @ytz @nicovandenhooff With respect to the EDA charts, it will be difficult to create the charts with the columns already transformed by one-hot encoding. I think it would be better if the OHE is done at the ML script stage. Let me know what you think.

**Comment by nicovandenhooff** [comment]
Yeah @arijc76 - that is a good point.  I guess since the output of the data pre-processing script is required to be the input of the EDA script then we would need to move the functions related to feature engineering into the ML script.  @ytz let me know if you have any other ideas though.

**Comment by ytz** [comment]
Hey @nicovandenhooff @arijc76 - good point. An easy way would be to output additional `train.csv` and `test.csv` just before the transformation step. I suspect the standardize feature might not be great for EDA charts too.

Edit: Done. See this pull request #14

**Comment by nicovandenhooff** [comment]
One minor thing I noticed in this script - we use the word `input` as a docopt parameter and then throughout the script as the input file path.  Would suggest changing this to something like `input_path` since `input` is a reserved word in python for user input.

Also - in the future I think it would be a good idea to complete code reviews in advance of accepting PRs (helps the collaboration aspect of the project).  Maybe we can discuss tomorrow if we want to do 2 reviews per PR or only 1 to be more efficient.

**Comment by ytz** [comment]
Thanks, good catch! Have made the changes (along with other documentation changes) in this PR #19

**Comment by nicovandenhooff** [comment]
@ytz just a heads up a couple things I noticed when trying to run the ML script on the data generated by this script (I should have tried this last night sorry)

- Changing revenue to yes/no from 1/0 breaks sklearn, I'll remove this line for now then add labels back when the confusion matrices are generated
- `feat_engineer` creates some `np.nans` since there are some training instances that have a `total_duration` of 0, which is causing some division by zero in the model process.  I'll just add a part to this function at the end to fill all nans with `0` (should be safe since there are no nans prior to feat engineering

Since they are quick edits I can just make them and then I'll include them in my pull request with the ML stuff later! 

Thanks
